import path from 'node:path';
import { mkdir, readFile, writeFile, symlink, access } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import type { FileEntryInfo, DocumentState } from '@graycode/contracts';
import { PlatformApplication } from '../../../apps/server/src/application';
import { ApplicationRouter } from '../../../apps/server/src/transport/router';
import { startHttpServer } from '../../../apps/server/src/transport/http';
import { fixture } from './fixtures';

test('文件操作保护草稿和目标版本，同步打开的文档，并按原始字节传输文件', async () => {
  const f = await fixture(); await f.store.close();
  const project = path.join(f.root, 'project'); const web = path.join(f.root, 'web');
  await mkdir(project); await mkdir(path.join(web, 'files/download'), { recursive: true });
  await writeFile(path.join(web, 'files/download/files'), '不能把文件接口当作公开静态资源');
  await writeFile(path.join(f.source, 'private.txt'), '工作区外的原文件');
  const app = await PlatformApplication.open({ dataDirectory: f.data });
  let http: Awaited<ReturnType<typeof startHttpServer>> | undefined;
  const router = new ApplicationRouter(app); const owner = { actorId: 'owner', clientId: 'desktop' }; const phone = { actorId: 'owner', clientId: 'phone' };
  const rpc = <T,>(method: string, params = {}, client = owner) => router.call(client, method, { workspaceId: 'files', ...params }) as Promise<T>;
  const inspect = (file: string) => rpc<FileEntryInfo>('files.inspect', { path: file });
  const resets: any[] = []; app.subscribe(event => { if (event.type === 'document.reset') resets.push(event); });
  try {
    const settings = app.settings.snapshot(); settings.settings.workspaces.push({ id: 'files', name: '文件操作', deviceId: 'local', directory: project });
    settings.settings.accounts.push({ id: 'guest', displayName: '普通成员', role: 'guest', effects: [], workspaceIds: [] });
    await app.settings.save({ settings: settings.settings, expectedRevision: settings.revision });
    await rpc('files.create', { path: 'folder', kind: 'directory' });
    await rpc('files.create', { path: 'folder/Example.txt', kind: 'file' });
    let doc = await rpc<DocumentState>('documents.open', { path: 'folder/Example.txt' });
    doc = await rpc<DocumentState>('documents.update', { path: doc.path, version: doc.version, text: '原始文档\n' });
    doc = await rpc<DocumentState>('documents.save', { path: doc.path, version: doc.version });
    await rpc('documents.open', { path: doc.path }, phone);
    doc = await rpc<DocumentState>('documents.update', { path: doc.path, version: doc.version, text: '尚未保存的内容' });
    const folder = await inspect('folder');
    await expect(rpc('files.move', { path: 'folder', target: 'src', expectedVersion: folder.version })).rejects.toThrow('DOCUMENT_DIRTY');
    await expect(rpc('files.remove', { path: 'folder', recursive: true, expectedVersion: folder.version })).rejects.toThrow('DOCUMENT_DIRTY');
    doc = await rpc<DocumentState>('documents.save', { path: doc.path, version: doc.version });
    const original = await inspect(doc.path);
    await rpc('files.move', { path: doc.path, target: 'folder/Renamed.txt', expectedVersion: original.version });
    expect(app.files.clientDocuments(owner.clientId, 'files')[0].path).toBe('folder/Renamed.txt');
    expect(app.files.clientDocuments(phone.clientId, 'files')[0]).toMatchObject({ path: 'folder/Renamed.txt', text: '尚未保存的内容', dirty: false });
    await rpc('files.move', { path: 'folder', target: 'src', expectedVersion: (await inspect('folder')).version });
    expect(app.files.clientDocuments(owner.clientId, 'files')[0].path).toBe('src/Renamed.txt');
    expect(resets.filter(event => event.document?.path === 'src/Renamed.txt')).toHaveLength(2);
    const stale = await inspect('src/Renamed.txt'); await writeFile(path.join(project, 'src/Renamed.txt'), '外部进程的新内容');
    await expect(rpc('files.remove', { path: stale.path, expectedVersion: stale.version })).rejects.toThrow('FILE_CONFLICT');
    expect(await readFile(path.join(project, stale.path), 'utf8')).toBe('外部进程的新内容');
    await expect(rpc('files.inspect', { path: 'src/Renamed.txt' }, { actorId: 'guest', clientId: 'guest' })).rejects.toThrow('Owner');
    await expect(rpc('files.create', { path: '../outside.txt', kind: 'file' })).rejects.toThrow();
    const token = randomBytes(32).toString('hex'); http = await startHttpServer(app, { token, clientDirectory: web });
    const origin = `http://127.0.0.1:${http.port}`;
    expect((await fetch(origin + '/files/download/files')).status).toBe(401);
    const login = await fetch(origin + '/auth/login', { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ token }) });
    const cookie = login.headers.get('set-cookie')!.split(';')[0]; const binary = Buffer.from([0, 1, 127, 128, 254, 255]);
    const file = '结果 文件.bin'; const uploadUrl = origin + '/files/upload/files?path=' + encodeURIComponent(file);
    const headers = { Cookie: cookie, Origin: origin, 'Content-Type': 'application/octet-stream', 'X-Graycode-File-Version': 'missing' };
    expect((await fetch(uploadUrl, { method: 'POST', headers, body: binary })).status).toBe(200);
    expect((await fetch(uploadUrl, { method: 'POST', headers, body: Buffer.from('不能覆盖') })).status).toBe(400);
    expect(await readFile(path.join(project, file))).toEqual(binary);
    const download = await fetch(origin + '/files/download/files?path=' + encodeURIComponent(file), { headers: { Cookie: cookie } });
    expect(download.headers.get('content-disposition')).toContain(encodeURIComponent(file));
    expect(Buffer.from(await download.arrayBuffer())).toEqual(binary);
    const partial = await fetch(origin + '/files/content/files?path=' + encodeURIComponent(file), { headers: { Cookie: cookie, Range: 'bytes=1-3' } });
    expect(partial.status).toBe(206); expect(Buffer.from(await partial.arrayBuffer())).toEqual(binary.subarray(1, 4));
    expect(partial.headers.get('content-range')).toBe('bytes 1-3/6');
    await symlink(f.source, path.join(project, 'outside-link'), process.platform === 'win32' ? 'junction' : 'dir');
    await expect(rpc('files.downloadInfo', { path: 'outside-link/private.txt' })).rejects.toThrow('outside');
    await rpc('files.remove', { path: 'outside-link', expectedVersion: (await inspect('outside-link')).version });
    expect(await readFile(path.join(f.source, 'private.txt'), 'utf8')).toBe('工作区外的原文件');
    await rpc('files.remove', { path: 'src', recursive: true, expectedVersion: (await inspect('src')).version });
    expect(app.files.clientDocuments(owner.clientId, 'files')).toHaveLength(0); expect(app.files.clientDocuments(phone.clientId, 'files')).toHaveLength(0);
    await expect(access(path.join(project, 'src'))).rejects.toThrow();
    await http.close();
    const pending = app.fileActions.upload('owner', 'files', 'closing.bin', 'missing', Buffer.alloc(1024 * 1024, 123));
    const closing = app.close(); await pending; await closing;
    expect((await readFile(path.join(project, 'closing.bin'))).byteLength).toBe(1024 * 1024);
  } finally { await http?.close(); await app.close(); await f.cleanup(); }
});
