import { createTerminalRuntime } from './processRunnerRuntime';
import * as shells from './shellConfig';
import * as output from './outputDecoder';
import * as prompts from './promptDescriptions';
import { TaskManager } from '../taskManager';
import { getAllWorkspaces, parseWorkspacePath } from '../utils';
import { getGlobalSettingsManager } from '../../core/settingsContext';
import { getDefaultExecuteCommandConfig } from '../../modules/settings/types/toolsTypes';
const getConfig = () => getGlobalSettingsManager()?.getExecuteCommandConfig() ?? getDefaultExecuteCommandConfig();
const runtime = createTerminalRuntime({ getConfig, shells, output, prompts, tasks: TaskManager, getAllWorkspaces, parseWorkspacePath });
export const { onTerminalOutput, onTerminalTaskEvent, createExecuteCommandTool, killTerminalProcess, cancelTerminalTask, detachRunningTerminalsToBackground, getTerminalOutput, getActiveTerminalProcesses, cleanupTerminals, registerExecuteCommand, getActiveTerminals } = runtime;
export type { TerminalProcess, TerminalOutputEvent } from './processRunnerRuntime';
