/**
 * AUTO-GENERATED by scripts/i18n-sync.mjs — 请勿手改！
 *
 * 共享词条生成物（单一来源：backend/i18n/langs/{zh-CN,en,ja}.ts + scripts/i18n-shared-manifest.json）。
 * 修改译文请改 backend 语言包；登记/调整共享映射请改 manifest，然后运行：
 *   node scripts/i18n-sync.mjs
 */

import backendEn from '../../../../../backend/i18n/langs/en';

const sharedEn = {
    app: {
        agentStopNotification: {
            actions: {
                continue: backendEn.notifications.windowsAgentStop.actionLabels.continue,
                executePlan: backendEn.notifications.windowsAgentStop.actionLabels.executePlan,
                generatePlan: backendEn.notifications.windowsAgentStop.actionLabels.generatePlan,
            },
        },
    },
    common: {
        completed: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
        confirm: backendEn.notifications.windowsAgentStop.actionLabels.genericConfirmation,
        date: backendEn.tools.reviewDocument.header.date,
        description: backendEn.tools.reviewDocument.finding.description,
        error: backendEn.modules.mcp.status.error,
        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
        hide: backendEn.tools.common.hide,
        resume: backendEn.notifications.windowsAgentStop.actionLabels.continue,
        show: backendEn.tools.common.show,
        status: backendEn.tools.reviewDocument.header.status,
        unknownError: backendEn.modules.api.chat.errors.unknownError,
    },
    components: {
        backgroundTasks: {
            completed: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
            failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
        },
        channels: {
            anthropic: {
                thinking: {
                    displaySummarized: backendEn.tools.reviewDocument.milestone.summary,
                    effortLow: backendEn.tools.reviewDocument.values.severity.low,
                    effortMedium: backendEn.tools.reviewDocument.values.severity.medium,
                },
            },
            gemini: {
                thinking: {
                    levelHigh: backendEn.tools.reviewDocument.values.severity.high,
                    levelLow: backendEn.tools.reviewDocument.values.severity.low,
                    levelMedium: backendEn.tools.reviewDocument.values.severity.medium,
                },
            },
            openai: {
                thinking: {
                    effortHigh: backendEn.tools.reviewDocument.values.severity.high,
                    effortLow: backendEn.tools.reviewDocument.values.severity.low,
                    effortMedium: backendEn.tools.reviewDocument.values.severity.medium,
                },
            },
        },
        common: {
            confirmDialog: {
                confirm: backendEn.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                title: backendEn.notifications.windowsAgentStop.actionLabels.genericConfirmation,
            },
        },
        input: {
            fileNotExists: backendEn.webview.errors.fileNotExists,
            notifications: {
                fileInOtherWorkspace: backendEn.webview.errors.fileInOtherWorkspace,
                fileNotInAnyWorkspace: backendEn.webview.errors.fileNotInAnyWorkspace,
            },
            promptContext: {
                readFailed: backendEn.webview.errors.readFileFailed,
            },
        },
        message: {
            checkpoint: {
                restoreResultFailed: backendEn.modules.checkpoint.errors.restoreFailed,
            },
            continue: {
                button: backendEn.notifications.windowsAgentStop.actionLabels.continue,
            },
            responseViewer: {
                status: backendEn.tools.reviewDocument.header.status,
                toolStatuses: {
                    error: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
            tool: {
                designCard: {
                    generatePlan: backendEn.notifications.windowsAgentStop.actionLabels.generatePlan,
                    openFileFailed: backendEn.webview.errors.openFileFailed,
                },
                error: backendEn.modules.mcp.status.error,
                openDiffFailed: backendEn.webview.errors.openDiffPreviewFailed,
                planCard: {
                    executePlan: backendEn.notifications.windowsAgentStop.actionLabels.executePlan,
                    openFileFailed: backendEn.webview.errors.openFileFailed,
                },
                progressCard: {
                    currentProgress: backendEn.tools.reviewDocument.summary.currentProgress,
                    issueError: backendEn.modules.mcp.status.error,
                    latestConclusion: backendEn.tools.reviewDocument.summary.latestConclusion,
                    milestoneStatusCompleted: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
                    milestoneStatusInProgress: backendEn.tools.reviewDocument.values.milestoneStatus.inProgress,
                    status: backendEn.tools.reviewDocument.milestone.status,
                    statusActive: backendEn.tools.reviewDocument.values.milestoneStatus.inProgress,
                    statusCompleted: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
                },
                reject: backendEn.tools.file.diffCodeLens.reject,
                rejectAll: backendEn.tools.file.diffCodeLens.rejectAll,
                reviewCard: {
                    categoryAccessibility: backendEn.tools.reviewDocument.values.category.accessibility,
                    categoryCss: backendEn.tools.reviewDocument.values.category.css,
                    categoryDocs: backendEn.tools.reviewDocument.values.category.docs,
                    categoryHtml: backendEn.tools.reviewDocument.values.category.html,
                    categoryJavascript: backendEn.tools.reviewDocument.values.category.javascript,
                    categoryMaintainability: backendEn.tools.reviewDocument.values.category.maintainability,
                    categoryOther: backendEn.tools.reviewDocument.values.category.other,
                    categoryPerformance: backendEn.tools.reviewDocument.values.category.performance,
                    categoryTest: backendEn.tools.reviewDocument.values.category.test,
                    changeDescription: backendEn.tools.reviewDocument.finding.description,
                    changeEvidence: backendEn.tools.reviewDocument.finding.evidenceFiles,
                    changeRecommendation: backendEn.tools.reviewDocument.finding.recommendation,
                    changeRelatedMilestoneIds: backendEn.tools.reviewDocument.finding.relatedMilestones,
                    changeSeverity: backendEn.tools.reviewDocument.finding.severity,
                    changeTrackingStatus: backendEn.tools.reviewDocument.finding.trackingStatus,
                    decision: backendEn.tools.reviewDocument.milestone.conclusion,
                    decisionAccepted: backendEn.tools.reviewDocument.values.overallDecision.accepted,
                    decisionConditionallyAccepted: backendEn.tools.reviewDocument.values.overallDecision.conditionallyAccepted,
                    decisionRejected: backendEn.tools.reviewDocument.values.overallDecision.rejected,
                    evidence: backendEn.tools.reviewDocument.milestone.evidenceFiles,
                    findings: backendEn.tools.reviewDocument.milestone.findings,
                    generatePlan: backendEn.notifications.windowsAgentStop.actionLabels.generatePlan,
                    issueError: backendEn.modules.mcp.status.error,
                    latestConclusion: backendEn.tools.reviewDocument.summary.latestConclusion,
                    modules: backendEn.tools.reviewDocument.summary.reviewedModules,
                    recommendedNextAction: backendEn.tools.reviewDocument.summary.recommendedNextAction,
                    severityHigh: backendEn.tools.reviewDocument.values.severity.high,
                    severityLow: backendEn.tools.reviewDocument.values.severity.low,
                    severityMedium: backendEn.tools.reviewDocument.values.severity.medium,
                    status: backendEn.tools.reviewDocument.header.status,
                    statusCompleted: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
                    statusInProgress: backendEn.tools.reviewDocument.values.milestoneStatus.inProgress,
                    tracking: backendEn.tools.reviewDocument.finding.trackingStatus,
                    trackingAcceptedRisk: backendEn.tools.reviewDocument.values.trackingStatus.acceptedRisk,
                    trackingDuplicate: backendEn.tools.reviewDocument.values.trackingStatus.duplicate,
                    trackingFixed: backendEn.tools.reviewDocument.values.trackingStatus.fixed,
                    trackingOpen: backendEn.tools.reviewDocument.values.trackingStatus.open,
                    trackingWontFix: backendEn.tools.reviewDocument.values.trackingStatus.wontFix,
                },
                todoPanel: {
                    statusCompleted: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
                    statusInProgress: backendEn.tools.reviewDocument.values.milestoneStatus.inProgress,
                },
            },
        },
        settings: {
            autoExec: {
                categories: {
                    other: backendEn.tools.reviewDocument.values.category.other,
                },
            },
            channelSettings: {
                dialog: {
                    delete: {
                        confirm: backendEn.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                    },
                },
                form: {
                    multimodal: {
                        document: backendEn.tools.reviewDocument.values.category.docs,
                    },
                },
                selector: {
                    confirm: backendEn.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                },
            },
            checkpoint: {
                sections: {
                    cleanup: {
                        manifestNote: backendEn.modules.checkpoint.restore.excludedNote,
                        phaseAfter: backendEn.modules.checkpoint.description.after,
                        phaseBefore: backendEn.modules.checkpoint.description.before,
                        progress: {
                            failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                        },
                    },
                    tools: {
                        afterLabel: backendEn.modules.checkpoint.description.after,
                        beforeLabel: backendEn.modules.checkpoint.description.before,
                    },
                },
            },
            contextSettings: {
                diagnostics: {
                    severity: {
                        error: backendEn.modules.mcp.status.error,
                    },
                },
            },
            dependencySettings: {
                progress: {
                    installSuccess: backendEn.modules.dependencies.progress.installSuccess,
                    unknownError: backendEn.modules.api.chat.errors.unknownError,
                },
            },
            mcp: {
                connected: backendEn.modules.mcp.status.connected,
                disconnected: backendEn.modules.mcp.status.disconnected,
                error: backendEn.modules.mcp.status.error,
            },
            mcpSettings: {
                form: {
                    description: backendEn.tools.reviewDocument.finding.description,
                    serverIdError: backendEn.modules.mcp.errors.invalidServerId,
                },
                serverCard: {
                    connecting: backendEn.modules.mcp.status.connecting,
                },
                status: {
                    connected: backendEn.modules.mcp.status.connected,
                    connecting: backendEn.modules.mcp.status.connecting,
                },
            },
            modelManager: {
                errors: {
                    addFailed: backendEn.modules.api.models.errors.addModelsFailed,
                    removeFailed: backendEn.modules.api.models.errors.removeModelFailed,
                    setActiveFailed: backendEn.modules.api.models.errors.setActiveModelFailed,
                },
            },
            promptSettings: {
                assemblyMode: {
                    description: backendEn.webview.promptSettings.assemblyMode.description,
                    entriesDescription: backendEn.webview.promptSettings.assemblyMode.entriesDescription,
                    entriesLabel: backendEn.webview.promptSettings.assemblyMode.entriesLabel,
                    legacyDescription: backendEn.webview.promptSettings.assemblyMode.legacyDescription,
                    legacyLabel: backendEn.webview.promptSettings.assemblyMode.legacyLabel,
                    title: backendEn.webview.promptSettings.assemblyMode.title,
                },
                dynamicSection: {
                    strategyDescription: backendEn.webview.promptSettings.dynamicSection.strategyDescription,
                    strategyPreserve: backendEn.webview.promptSettings.dynamicSection.strategyPreserve,
                    strategyPreserveWarning: backendEn.webview.promptSettings.dynamicSection.strategyPreserveWarning,
                    strategySingle: backendEn.webview.promptSettings.dynamicSection.strategySingle,
                    strategyTitle: backendEn.webview.promptSettings.dynamicSection.strategyTitle,
                    strategyVarsPrefix: backendEn.webview.promptSettings.dynamicSection.strategyVarsPrefix,
                    strategyVarsSeparator: backendEn.webview.promptSettings.dynamicSection.strategyVarsSeparator,
                    strategyVarsSuffix: backendEn.webview.promptSettings.dynamicSection.strategyVarsSuffix,
                    strategyVarsWarning: backendEn.webview.promptSettings.dynamicSection.strategyVarsWarning,
                },
            },
            subagents: {
                description: backendEn.tools.reviewDocument.finding.description,
            },
            toolSettings: {
                common: {
                    error: backendEn.modules.mcp.status.error,
                },
                files: {
                    applyDiff: {
                        diffGuardWarning: backendEn.tools.file.diffManager.diffGuardWarning,
                    },
                },
                terminal: {
                    executeCommand: {
                        execTimeout: backendEn.tools.errors.timeout,
                    },
                },
            },
            toolsSettings: {
                categories: {
                    other: backendEn.tools.reviewDocument.values.category.other,
                },
            },
        },
        subagents: {
            monitor: {
                resume: backendEn.notifications.windowsAgentStop.actionLabels.continue,
                status: {
                    completed: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
                    failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
        },
        tools: {
            automation: {
                accepted: backendEn.tools.automation.accepted,
                accessibilityUnavailable: backendEn.tools.automation.accessibilityUnavailable,
                actions: {
                    acquire: backendEn.tools.automation.actions.acquire,
                    back: backendEn.tools.automation.actions.back,
                    cancel: backendEn.tools.automation.actions.cancel,
                    click: backendEn.tools.automation.actions.click,
                    close: backendEn.tools.automation.actions.close,
                    collapse: backendEn.tools.automation.actions.collapse,
                    create: backendEn.tools.automation.actions.create,
                    download: backendEn.tools.automation.actions.download,
                    drag: backendEn.tools.automation.actions.drag,
                    expand: backendEn.tools.automation.actions.expand,
                    expression: backendEn.tools.automation.actions.expression,
                    fill: backendEn.tools.automation.actions.fill,
                    focusElement: backendEn.tools.automation.actions.focusElement,
                    focusWindow: backendEn.tools.automation.actions.focusWindow,
                    forward: backendEn.tools.automation.actions.forward,
                    invoke: backendEn.tools.automation.actions.invoke,
                    key: backendEn.tools.automation.actions.key,
                    list: backendEn.tools.automation.actions.list,
                    logs: backendEn.tools.automation.actions.logs,
                    look: backendEn.tools.automation.actions.look,
                    navigate: backendEn.tools.automation.actions.navigate,
                    parameters: backendEn.tools.automation.actions.parameters,
                    play: backendEn.tools.automation.actions.play,
                    press: backendEn.tools.automation.actions.press,
                    query: backendEn.tools.automation.actions.query,
                    read: backendEn.tools.automation.actions.read,
                    release: backendEn.tools.automation.actions.release,
                    reload: backendEn.tools.automation.actions.reload,
                    resume: backendEn.tools.automation.actions.resume,
                    screenshot: backendEn.tools.automation.actions.screenshot,
                    scroll: backendEn.tools.automation.actions.scroll,
                    select: backendEn.tools.automation.actions.select,
                    setValue: backendEn.tools.automation.actions.setValue,
                    show: backendEn.tools.automation.actions.show,
                    snapshot: backendEn.tools.automation.actions.snapshot,
                    stat: backendEn.tools.automation.actions.stat,
                    status: backendEn.tools.automation.actions.status,
                    toggle: backendEn.tools.automation.actions.toggle,
                    type: backendEn.tools.automation.actions.type,
                    upload: backendEn.tools.automation.actions.upload,
                },
                activeTab: backendEn.tools.automation.activeTab,
                applied: backendEn.tools.automation.applied,
                attachments: backendEn.tools.automation.attachments,
                available: backendEn.tools.automation.available,
                capturedAt: backendEn.tools.automation.capturedAt,
                characterRange: backendEn.tools.automation.characterRange,
                confirmedCommand: backendEn.tools.automation.confirmedCommand,
                control: backendEn.tools.automation.control,
                controlActive: backendEn.tools.automation.controlActive,
                controlInactive: backendEn.tools.automation.controlInactive,
                controlledBy: backendEn.tools.automation.controlledBy,
                controller: backendEn.tools.automation.controller,
                currentCommand: backendEn.tools.automation.currentCommand,
                currentPage: backendEn.tools.automation.currentPage,
                defaultValue: backendEn.tools.automation.defaultValue,
                dimensions: backendEn.tools.automation.dimensions,
                dispatching: backendEn.tools.automation.dispatching,
                displays: backendEn.tools.automation.displays,
                downloaded: backendEn.tools.automation.downloaded,
                duration: backendEn.tools.automation.duration,
                emptyText: backendEn.tools.automation.emptyText,
                encoding: backendEn.tools.automation.encoding,
                endOfDocument: backendEn.tools.automation.endOfDocument,
                expressions: backendEn.tools.automation.expressions,
                focusedElement: backendEn.tools.automation.focusedElement,
                foreground: backendEn.tools.automation.foreground,
                front: backendEn.tools.automation.front,
                imageCoordinates: backendEn.tools.automation.imageCoordinates,
                loading: backendEn.tools.automation.loading,
                logs: backendEn.tools.automation.logs,
                lookAngle: backendEn.tools.automation.lookAngle,
                minimized: backendEn.tools.automation.minimized,
                nextCursor: backendEn.tools.automation.nextCursor,
                nextOffset: backendEn.tools.automation.nextOffset,
                noAttachments: backendEn.tools.automation.noAttachments,
                noElements: backendEn.tools.automation.noElements,
                noLogs: backendEn.tools.automation.noLogs,
                noPet: backendEn.tools.automation.noPet,
                noTabs: backendEn.tools.automation.noTabs,
                noWindows: backendEn.tools.automation.noWindows,
                notAccepted: backendEn.tools.automation.notAccepted,
                notApplied: backendEn.tools.automation.notApplied,
                observation: backendEn.tools.automation.observation,
                observationUnavailable: backendEn.tools.automation.observationUnavailable,
                operationStatus: backendEn.tools.automation.operationStatus,
                operationUnknown: backendEn.tools.automation.operationUnknown,
                parameterRanges: backendEn.tools.automation.parameterRanges,
                petActions: backendEn.tools.automation.petActions,
                petModel: backendEn.tools.automation.petModel,
                phases: {
                    failed: backendEn.tools.automation.phases.failed,
                    loading: backendEn.tools.automation.phases.loading,
                    ready: backendEn.tools.automation.phases.ready,
                    unloaded: backendEn.tools.automation.phases.unloaded,
                },
                primaryDisplay: backendEn.tools.automation.primaryDisplay,
                profiles: backendEn.tools.automation.profiles,
                range: backendEn.tools.automation.range,
                reason: backendEn.tools.automation.reason,
                renderer: backendEn.tools.automation.renderer,
                repeated: backendEn.tools.automation.repeated,
                requestId: backendEn.tools.automation.requestId,
                size: backendEn.tools.automation.size,
                stopShortcut: backendEn.tools.automation.stopShortcut,
                stopped: backendEn.tools.automation.stopped,
                truncated: backendEn.tools.automation.truncated,
                unavailable: backendEn.tools.automation.unavailable,
                untitled: backendEn.tools.automation.untitled,
                uploaded: backendEn.tools.automation.uploaded,
                userControlled: backendEn.tools.automation.userControlled,
                visible: backendEn.tools.automation.visible,
                windowVisible: backendEn.tools.automation.windowVisible,
            },
            error: backendEn.modules.mcp.status.error,
            file: {
                createDirectoryPanel: {
                    failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                },
                deleteFilePanel: {
                    failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
            media: {
                cropImagePanel: {
                    status: {
                        error: backendEn.modules.mcp.status.error,
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                generateImagePanel: {
                    status: {
                        error: backendEn.modules.mcp.status.error,
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                removeBackgroundPanel: {
                    status: {
                        error: backendEn.modules.mcp.status.error,
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                resizeImagePanel: {
                    status: {
                        error: backendEn.modules.mcp.status.error,
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                rotateImagePanel: {
                    status: {
                        error: backendEn.modules.mcp.status.error,
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
            },
            platform: {
                file: {
                    actions: {
                        delete: backendEn.tools.platform.file.actions.delete,
                        edit: backendEn.tools.platform.file.actions.edit,
                        list: backendEn.tools.platform.file.actions.list,
                        read: backendEn.tools.platform.file.actions.read,
                        write: backendEn.tools.platform.file.actions.write,
                    },
                    after: backendEn.tools.platform.file.after,
                    before: backendEn.tools.platform.file.before,
                    deleted: backendEn.tools.platform.file.deleted,
                    empty: backendEn.tools.platform.file.empty,
                    matchLimit: backendEn.tools.platform.file.matchLimit,
                    matches: backendEn.tools.platform.file.matches,
                    nextLine: backendEn.tools.platform.file.nextLine,
                    noMatches: backendEn.tools.platform.file.noMatches,
                    range: backendEn.tools.platform.file.range,
                    requested: backendEn.tools.platform.file.requested,
                    saved: backendEn.tools.platform.file.saved,
                    scanLimit: backendEn.tools.platform.file.scanLimit,
                    scanned: backendEn.tools.platform.file.scanned,
                },
                memory: {
                    affected: backendEn.tools.platform.memory.affected,
                    append: backendEn.tools.platform.memory.append,
                    apply: backendEn.tools.platform.memory.apply,
                    confidence: {
                        confirmed: backendEn.tools.platform.memory.confidence.confirmed,
                        disputed: backendEn.tools.platform.memory.confidence.disputed,
                        inferred: backendEn.tools.platform.memory.confidence.inferred,
                    },
                    conflicts: backendEn.tools.platform.memory.conflicts,
                    dependencies: backendEn.tools.platform.memory.dependencies,
                    empty: backendEn.tools.platform.memory.empty,
                    kinds: {
                        event: backendEn.tools.platform.memory.kinds.event,
                        experience: backendEn.tools.platform.memory.kinds.experience,
                        fact: backendEn.tools.platform.memory.kinds.fact,
                        preference: backendEn.tools.platform.memory.kinds.preference,
                        procedure: backendEn.tools.platform.memory.kinds.procedure,
                        project: backendEn.tools.platform.memory.kinds.project,
                        summary: backendEn.tools.platform.memory.kinds.summary,
                    },
                    omitted: backendEn.tools.platform.memory.omitted,
                    origins: {
                        fiction: backendEn.tools.platform.memory.origins.fiction,
                        import: backendEn.tools.platform.memory.origins.import,
                        model: backendEn.tools.platform.memory.origins.model,
                        tool: backendEn.tools.platform.memory.origins.tool,
                        user: backendEn.tools.platform.memory.origins.user,
                    },
                    pageRange: backendEn.tools.platform.memory.pageRange,
                    preview: backendEn.tools.platform.memory.preview,
                    previewIds: backendEn.tools.platform.memory.previewIds,
                    recordPage: backendEn.tools.platform.memory.recordPage,
                    records: backendEn.tools.platform.memory.records,
                    removed: backendEn.tools.platform.memory.removed,
                    requested: backendEn.tools.platform.memory.requested,
                    requiredBudget: backendEn.tools.platform.memory.requiredBudget,
                    retract: backendEn.tools.platform.memory.retract,
                    root: backendEn.tools.platform.memory.root,
                    saved: backendEn.tools.platform.memory.saved,
                    scopeKinds: {
                        group: backendEn.tools.platform.memory.scopeKinds.group,
                        library: backendEn.tools.platform.memory.scopeKinds.library,
                        personal: backendEn.tools.platform.memory.scopeKinds.personal,
                        workspace: backendEn.tools.platform.memory.scopeKinds.workspace,
                    },
                    scopes: backendEn.tools.platform.memory.scopes,
                    source: backendEn.tools.platform.memory.source,
                    sourcePage: backendEn.tools.platform.memory.sourcePage,
                    sources: backendEn.tools.platform.memory.sources,
                    topics: backendEn.tools.platform.memory.topics,
                    truncated: backendEn.tools.platform.memory.truncated,
                    unavailable: backendEn.tools.platform.memory.unavailable,
                },
                nextCursor: backendEn.tools.platform.nextCursor,
                nextOffset: backendEn.tools.platform.nextOffset,
                noData: backendEn.tools.platform.noData,
                partial: backendEn.tools.platform.partial,
                process: {
                    actions: {
                        input: backendEn.tools.platform.process.actions.input,
                        read: backendEn.tools.platform.process.actions.read,
                        stop: backendEn.tools.platform.process.actions.stop,
                    },
                    exited: backendEn.tools.platform.process.exited,
                    input: backendEn.tools.platform.process.input,
                    noOutput: backendEn.tools.platform.process.noOutput,
                    output: backendEn.tools.platform.process.output,
                    running: backendEn.tools.platform.process.running,
                    truncated: backendEn.tools.platform.process.truncated,
                    unknown: backendEn.tools.platform.process.unknown,
                },
                team: {
                    actions: {
                        claim: backendEn.tools.platform.team.actions.claim,
                        claim_ready: backendEn.tools.platform.team.actions.claim_ready,
                        complete: backendEn.tools.platform.team.actions.complete,
                        create: backendEn.tools.platform.team.actions.create,
                        get: backendEn.tools.platform.team.actions.get,
                        list: backendEn.tools.platform.team.actions.list,
                        release: backendEn.tools.platform.team.actions.release,
                        set_dependencies: backendEn.tools.platform.team.actions.set_dependencies,
                    },
                    assigned: backendEn.tools.platform.team.assigned,
                    blockedBy: backendEn.tools.platform.team.blockedBy,
                    dependencies: backendEn.tools.platform.team.dependencies,
                    empty: backendEn.tools.platform.team.empty,
                    emptyEvents: backendEn.tools.platform.team.emptyEvents,
                    events: {
                        member_changed: backendEn.tools.platform.team.events.member_changed,
                        message_queued: backendEn.tools.platform.team.events.message_queued,
                        task_claimed: backendEn.tools.platform.team.events.task_claimed,
                        task_completed: backendEn.tools.platform.team.events.task_completed,
                        task_created: backendEn.tools.platform.team.events.task_created,
                        task_dependencies_changed: backendEn.tools.platform.team.events.task_dependencies_changed,
                        task_released: backendEn.tools.platform.team.events.task_released,
                    },
                    moreEvents: backendEn.tools.platform.team.moreEvents,
                    nextTasks: backendEn.tools.platform.team.nextTasks,
                    noProgress: backendEn.tools.platform.team.noProgress,
                    noReady: backendEn.tools.platform.team.noReady,
                    ready: backendEn.tools.platform.team.ready,
                    reasons: {
                        events: backendEn.tools.platform.team.reasons.events,
                        no_progress: backendEn.tools.platform.team.reasons.no_progress,
                        ready_work: backendEn.tools.platform.team.reasons.ready_work,
                        timeout: backendEn.tools.platform.team.reasons.timeout,
                    },
                    task: backendEn.tools.platform.team.task,
                    unclaimed: backendEn.tools.platform.team.unclaimed,
                },
                version: backendEn.tools.platform.version,
            },
            presentation: {
                appendedContent: backendEn.tools.presentation.appendedContent,
                characters: backendEn.tools.presentation.characters,
                contentUnavailable: backendEn.tools.presentation.contentUnavailable,
                historyMessages: backendEn.tools.presentation.historyMessages,
                invalidatedNote: backendEn.tools.presentation.invalidatedNote,
                mainAgent: backendEn.tools.presentation.mainAgent,
                messageBody: backendEn.tools.presentation.messageBody,
                messageSaved: backendEn.tools.presentation.messageSaved,
                moreHistory: backendEn.tools.presentation.moreHistory,
                noteContent: backendEn.tools.presentation.noteContent,
                noteDirectory: backendEn.tools.presentation.noteDirectory,
                partialContent: backendEn.tools.presentation.partialContent,
                recipient: backendEn.tools.presentation.recipient,
            },
            reject: backendEn.tools.file.diffCodeLens.reject,
            subagents: {
                completed: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
            },
            terminal: {
                executeCommandPanel: {
                    status: {
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
            },
        },
    },
    composables: {
        useAttachments: {
            errors: {
                readFileFailed: backendEn.webview.errors.readFileFailed,
            },
        },
    },
    errors: {
        cancelled: backendEn.errors.cancelled,
        unknown: backendEn.errors.unknown,
    },
    stores: {
        chatStore: {
            errors: {
                restoreCheckpointFailed: backendEn.modules.checkpoint.errors.restoreFailed,
                unknownError: backendEn.modules.api.chat.errors.unknownError,
            },
        },
        terminalStore: {
            errors: {
                killTerminalFailed: backendEn.webview.errors.killTerminalFailed,
            },
        },
    },
};

export default sharedEn;
