/**
 * AUTO-GENERATED by scripts/i18n-sync.mjs — 请勿手改！
 *
 * 共享词条生成物（单一来源：backend/i18n/langs/{zh-CN,en,ja}.ts + scripts/i18n-shared-manifest.json）。
 * 修改译文请改 backend 语言包；登记/调整共享映射请改 manifest，然后运行：
 *   node scripts/i18n-sync.mjs
 */

import backendJa from '../../../../../backend/i18n/langs/ja';

const sharedJa = {
    app: {
        agentStopNotification: {
            actions: {
                continue: backendJa.notifications.windowsAgentStop.actionLabels.continue,
                executePlan: backendJa.notifications.windowsAgentStop.actionLabels.executePlan,
                generatePlan: backendJa.notifications.windowsAgentStop.actionLabels.generatePlan,
            },
        },
    },
    common: {
        completed: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
        confirm: backendJa.notifications.windowsAgentStop.actionLabels.genericConfirmation,
        date: backendJa.tools.reviewDocument.header.date,
        description: backendJa.tools.reviewDocument.finding.description,
        error: backendJa.modules.mcp.status.error,
        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
        hide: backendJa.tools.common.hide,
        resume: backendJa.notifications.windowsAgentStop.actionLabels.continue,
        show: backendJa.tools.common.show,
        status: backendJa.tools.reviewDocument.header.status,
        unknownError: backendJa.modules.api.chat.errors.unknownError,
    },
    components: {
        backgroundTasks: {
            completed: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
            failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
        },
        channels: {
            anthropic: {
                thinking: {
                    displaySummarized: backendJa.tools.reviewDocument.milestone.summary,
                    effortLow: backendJa.tools.reviewDocument.values.severity.low,
                    effortMedium: backendJa.tools.reviewDocument.values.severity.medium,
                },
            },
            gemini: {
                thinking: {
                    levelHigh: backendJa.tools.reviewDocument.values.severity.high,
                    levelLow: backendJa.tools.reviewDocument.values.severity.low,
                    levelMedium: backendJa.tools.reviewDocument.values.severity.medium,
                },
            },
            openai: {
                thinking: {
                    effortHigh: backendJa.tools.reviewDocument.values.severity.high,
                    effortLow: backendJa.tools.reviewDocument.values.severity.low,
                    effortMedium: backendJa.tools.reviewDocument.values.severity.medium,
                },
            },
        },
        common: {
            confirmDialog: {
                confirm: backendJa.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                title: backendJa.notifications.windowsAgentStop.actionLabels.genericConfirmation,
            },
        },
        input: {
            fileNotExists: backendJa.webview.errors.fileNotExists,
            notifications: {
                fileInOtherWorkspace: backendJa.webview.errors.fileInOtherWorkspace,
                fileNotInAnyWorkspace: backendJa.webview.errors.fileNotInAnyWorkspace,
            },
            promptContext: {
                readFailed: backendJa.webview.errors.readFileFailed,
            },
        },
        message: {
            checkpoint: {
                restoreResultFailed: backendJa.modules.checkpoint.errors.restoreFailed,
            },
            continue: {
                button: backendJa.notifications.windowsAgentStop.actionLabels.continue,
            },
            responseViewer: {
                status: backendJa.tools.reviewDocument.header.status,
                toolStatuses: {
                    error: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
            tool: {
                designCard: {
                    generatePlan: backendJa.notifications.windowsAgentStop.actionLabels.generatePlan,
                    openFileFailed: backendJa.webview.errors.openFileFailed,
                },
                error: backendJa.modules.mcp.status.error,
                openDiffFailed: backendJa.webview.errors.openDiffPreviewFailed,
                planCard: {
                    executePlan: backendJa.notifications.windowsAgentStop.actionLabels.executePlan,
                    openFileFailed: backendJa.webview.errors.openFileFailed,
                },
                progressCard: {
                    currentProgress: backendJa.tools.reviewDocument.summary.currentProgress,
                    issueError: backendJa.modules.mcp.status.error,
                    latestConclusion: backendJa.tools.reviewDocument.summary.latestConclusion,
                    milestoneStatusCompleted: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
                    milestoneStatusInProgress: backendJa.tools.reviewDocument.values.milestoneStatus.inProgress,
                    status: backendJa.tools.reviewDocument.milestone.status,
                    statusActive: backendJa.tools.reviewDocument.values.milestoneStatus.inProgress,
                    statusCompleted: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
                },
                reject: backendJa.tools.file.diffCodeLens.reject,
                rejectAll: backendJa.tools.file.diffCodeLens.rejectAll,
                reviewCard: {
                    categoryAccessibility: backendJa.tools.reviewDocument.values.category.accessibility,
                    categoryCss: backendJa.tools.reviewDocument.values.category.css,
                    categoryDocs: backendJa.tools.reviewDocument.values.category.docs,
                    categoryHtml: backendJa.tools.reviewDocument.values.category.html,
                    categoryJavascript: backendJa.tools.reviewDocument.values.category.javascript,
                    categoryMaintainability: backendJa.tools.reviewDocument.values.category.maintainability,
                    categoryOther: backendJa.tools.reviewDocument.values.category.other,
                    categoryPerformance: backendJa.tools.reviewDocument.values.category.performance,
                    categoryTest: backendJa.tools.reviewDocument.values.category.test,
                    changeDescription: backendJa.tools.reviewDocument.finding.description,
                    changeEvidence: backendJa.tools.reviewDocument.finding.evidenceFiles,
                    changeRecommendation: backendJa.tools.reviewDocument.finding.recommendation,
                    changeRelatedMilestoneIds: backendJa.tools.reviewDocument.finding.relatedMilestones,
                    changeSeverity: backendJa.tools.reviewDocument.finding.severity,
                    changeTrackingStatus: backendJa.tools.reviewDocument.finding.trackingStatus,
                    decision: backendJa.tools.reviewDocument.milestone.conclusion,
                    decisionAccepted: backendJa.tools.reviewDocument.values.overallDecision.accepted,
                    decisionConditionallyAccepted: backendJa.tools.reviewDocument.values.overallDecision.conditionallyAccepted,
                    decisionRejected: backendJa.tools.reviewDocument.values.overallDecision.rejected,
                    evidence: backendJa.tools.reviewDocument.milestone.evidenceFiles,
                    findings: backendJa.tools.reviewDocument.milestone.findings,
                    generatePlan: backendJa.notifications.windowsAgentStop.actionLabels.generatePlan,
                    issueError: backendJa.modules.mcp.status.error,
                    latestConclusion: backendJa.tools.reviewDocument.summary.latestConclusion,
                    modules: backendJa.tools.reviewDocument.summary.reviewedModules,
                    recommendedNextAction: backendJa.tools.reviewDocument.summary.recommendedNextAction,
                    severityHigh: backendJa.tools.reviewDocument.values.severity.high,
                    severityLow: backendJa.tools.reviewDocument.values.severity.low,
                    severityMedium: backendJa.tools.reviewDocument.values.severity.medium,
                    status: backendJa.tools.reviewDocument.header.status,
                    statusCompleted: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
                    statusInProgress: backendJa.tools.reviewDocument.values.milestoneStatus.inProgress,
                    tracking: backendJa.tools.reviewDocument.finding.trackingStatus,
                    trackingAcceptedRisk: backendJa.tools.reviewDocument.values.trackingStatus.acceptedRisk,
                    trackingDuplicate: backendJa.tools.reviewDocument.values.trackingStatus.duplicate,
                    trackingFixed: backendJa.tools.reviewDocument.values.trackingStatus.fixed,
                    trackingOpen: backendJa.tools.reviewDocument.values.trackingStatus.open,
                    trackingWontFix: backendJa.tools.reviewDocument.values.trackingStatus.wontFix,
                },
                todoPanel: {
                    statusCompleted: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
                    statusInProgress: backendJa.tools.reviewDocument.values.milestoneStatus.inProgress,
                },
            },
        },
        settings: {
            autoExec: {
                categories: {
                    other: backendJa.tools.reviewDocument.values.category.other,
                },
            },
            backgroundGalleryPolicy: backendJa.modules.settings.backgroundGalleryPolicy,
            channelSettings: {
                dialog: {
                    delete: {
                        confirm: backendJa.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                    },
                },
                form: {
                    multimodal: {
                        document: backendJa.tools.reviewDocument.values.category.docs,
                    },
                    strictTools: {
                        support: {
                            openaiResponses: backendJa.tools.presentation.strictToolsOpenaiResponses,
                        },
                    },
                },
                selector: {
                    confirm: backendJa.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                },
            },
            checkpoint: {
                sections: {
                    cleanup: {
                        manifestNote: backendJa.modules.checkpoint.restore.excludedNote,
                        phaseAfter: backendJa.modules.checkpoint.description.after,
                        phaseBefore: backendJa.modules.checkpoint.description.before,
                        progress: {
                            failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                        },
                    },
                    tools: {
                        afterLabel: backendJa.modules.checkpoint.description.after,
                        beforeLabel: backendJa.modules.checkpoint.description.before,
                    },
                },
            },
            contextSettings: {
                diagnostics: {
                    severity: {
                        error: backendJa.modules.mcp.status.error,
                    },
                },
            },
            dependencySettings: {
                progress: {
                    installSuccess: backendJa.modules.dependencies.progress.installSuccess,
                    unknownError: backendJa.modules.api.chat.errors.unknownError,
                },
            },
            mcp: {
                connected: backendJa.modules.mcp.status.connected,
                disconnected: backendJa.modules.mcp.status.disconnected,
                error: backendJa.modules.mcp.status.error,
            },
            mcpSettings: {
                form: {
                    description: backendJa.tools.reviewDocument.finding.description,
                    serverIdError: backendJa.modules.mcp.errors.invalidServerId,
                },
                serverCard: {
                    connecting: backendJa.modules.mcp.status.connecting,
                },
                status: {
                    connected: backendJa.modules.mcp.status.connected,
                    connecting: backendJa.modules.mcp.status.connecting,
                },
            },
            modelManager: {
                errors: {
                    addFailed: backendJa.modules.api.models.errors.addModelsFailed,
                    removeFailed: backendJa.modules.api.models.errors.removeModelFailed,
                    setActiveFailed: backendJa.modules.api.models.errors.setActiveModelFailed,
                },
            },
            promptSettings: {
                assemblyMode: {
                    description: backendJa.webview.promptSettings.assemblyMode.description,
                    entriesDescription: backendJa.webview.promptSettings.assemblyMode.entriesDescription,
                    entriesLabel: backendJa.webview.promptSettings.assemblyMode.entriesLabel,
                    legacyDescription: backendJa.webview.promptSettings.assemblyMode.legacyDescription,
                    legacyLabel: backendJa.webview.promptSettings.assemblyMode.legacyLabel,
                    title: backendJa.webview.promptSettings.assemblyMode.title,
                },
                dynamicSection: {
                    strategyDescription: backendJa.webview.promptSettings.dynamicSection.strategyDescription,
                    strategyPreserve: backendJa.webview.promptSettings.dynamicSection.strategyPreserve,
                    strategyPreserveWarning: backendJa.webview.promptSettings.dynamicSection.strategyPreserveWarning,
                    strategySingle: backendJa.webview.promptSettings.dynamicSection.strategySingle,
                    strategyTitle: backendJa.webview.promptSettings.dynamicSection.strategyTitle,
                    strategyVarsPrefix: backendJa.webview.promptSettings.dynamicSection.strategyVarsPrefix,
                    strategyVarsSeparator: backendJa.webview.promptSettings.dynamicSection.strategyVarsSeparator,
                    strategyVarsSuffix: backendJa.webview.promptSettings.dynamicSection.strategyVarsSuffix,
                    strategyVarsWarning: backendJa.webview.promptSettings.dynamicSection.strategyVarsWarning,
                },
            },
            subagents: {
                description: backendJa.tools.reviewDocument.finding.description,
            },
            toolSettings: {
                common: {
                    error: backendJa.modules.mcp.status.error,
                },
                files: {
                    applyDiff: {
                        diffGuardWarning: backendJa.tools.file.diffManager.diffGuardWarning,
                    },
                },
                terminal: {
                    executeCommand: {
                        execTimeout: backendJa.tools.errors.timeout,
                    },
                },
            },
            toolsSettings: {
                categories: {
                    other: backendJa.tools.reviewDocument.values.category.other,
                },
            },
        },
        subagents: {
            monitor: {
                resume: backendJa.notifications.windowsAgentStop.actionLabels.continue,
                status: {
                    completed: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
                    failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
        },
        tools: {
            automation: {
                accepted: backendJa.tools.automation.accepted,
                accessibilityUnavailable: backendJa.tools.automation.accessibilityUnavailable,
                actions: {
                    acquire: backendJa.tools.automation.actions.acquire,
                    back: backendJa.tools.automation.actions.back,
                    cancel: backendJa.tools.automation.actions.cancel,
                    click: backendJa.tools.automation.actions.click,
                    close: backendJa.tools.automation.actions.close,
                    collapse: backendJa.tools.automation.actions.collapse,
                    create: backendJa.tools.automation.actions.create,
                    download: backendJa.tools.automation.actions.download,
                    drag: backendJa.tools.automation.actions.drag,
                    expand: backendJa.tools.automation.actions.expand,
                    expression: backendJa.tools.automation.actions.expression,
                    fill: backendJa.tools.automation.actions.fill,
                    focusElement: backendJa.tools.automation.actions.focusElement,
                    focusWindow: backendJa.tools.automation.actions.focusWindow,
                    forward: backendJa.tools.automation.actions.forward,
                    invoke: backendJa.tools.automation.actions.invoke,
                    key: backendJa.tools.automation.actions.key,
                    list: backendJa.tools.automation.actions.list,
                    logs: backendJa.tools.automation.actions.logs,
                    look: backendJa.tools.automation.actions.look,
                    navigate: backendJa.tools.automation.actions.navigate,
                    parameters: backendJa.tools.automation.actions.parameters,
                    play: backendJa.tools.automation.actions.play,
                    press: backendJa.tools.automation.actions.press,
                    query: backendJa.tools.automation.actions.query,
                    read: backendJa.tools.automation.actions.read,
                    release: backendJa.tools.automation.actions.release,
                    reload: backendJa.tools.automation.actions.reload,
                    resume: backendJa.tools.automation.actions.resume,
                    screenshot: backendJa.tools.automation.actions.screenshot,
                    scroll: backendJa.tools.automation.actions.scroll,
                    select: backendJa.tools.automation.actions.select,
                    setValue: backendJa.tools.automation.actions.setValue,
                    show: backendJa.tools.automation.actions.show,
                    snapshot: backendJa.tools.automation.actions.snapshot,
                    stat: backendJa.tools.automation.actions.stat,
                    status: backendJa.tools.automation.actions.status,
                    toggle: backendJa.tools.automation.actions.toggle,
                    type: backendJa.tools.automation.actions.type,
                    upload: backendJa.tools.automation.actions.upload,
                },
                activeTab: backendJa.tools.automation.activeTab,
                applied: backendJa.tools.automation.applied,
                attachments: backendJa.tools.automation.attachments,
                available: backendJa.tools.automation.available,
                capturedAt: backendJa.tools.automation.capturedAt,
                characterRange: backendJa.tools.automation.characterRange,
                confirmedCommand: backendJa.tools.automation.confirmedCommand,
                control: backendJa.tools.automation.control,
                controlActive: backendJa.tools.automation.controlActive,
                controlInactive: backendJa.tools.automation.controlInactive,
                controlledBy: backendJa.tools.automation.controlledBy,
                controller: backendJa.tools.automation.controller,
                currentCommand: backendJa.tools.automation.currentCommand,
                currentPage: backendJa.tools.automation.currentPage,
                defaultValue: backendJa.tools.automation.defaultValue,
                dimensions: backendJa.tools.automation.dimensions,
                dispatching: backendJa.tools.automation.dispatching,
                displays: backendJa.tools.automation.displays,
                downloaded: backendJa.tools.automation.downloaded,
                duration: backendJa.tools.automation.duration,
                emptyText: backendJa.tools.automation.emptyText,
                encoding: backendJa.tools.automation.encoding,
                endOfDocument: backendJa.tools.automation.endOfDocument,
                expressions: backendJa.tools.automation.expressions,
                focusedElement: backendJa.tools.automation.focusedElement,
                foreground: backendJa.tools.automation.foreground,
                front: backendJa.tools.automation.front,
                imageCoordinates: backendJa.tools.automation.imageCoordinates,
                loading: backendJa.tools.automation.loading,
                logs: backendJa.tools.automation.logs,
                lookAngle: backendJa.tools.automation.lookAngle,
                minimized: backendJa.tools.automation.minimized,
                nextCursor: backendJa.tools.automation.nextCursor,
                nextOffset: backendJa.tools.automation.nextOffset,
                noAttachments: backendJa.tools.automation.noAttachments,
                noElements: backendJa.tools.automation.noElements,
                noLogs: backendJa.tools.automation.noLogs,
                noPet: backendJa.tools.automation.noPet,
                noTabs: backendJa.tools.automation.noTabs,
                noWindows: backendJa.tools.automation.noWindows,
                notAccepted: backendJa.tools.automation.notAccepted,
                notApplied: backendJa.tools.automation.notApplied,
                observation: backendJa.tools.automation.observation,
                observationUnavailable: backendJa.tools.automation.observationUnavailable,
                operationStatus: backendJa.tools.automation.operationStatus,
                operationUnknown: backendJa.tools.automation.operationUnknown,
                parameterRanges: backendJa.tools.automation.parameterRanges,
                petActions: backendJa.tools.automation.petActions,
                petModel: backendJa.tools.automation.petModel,
                phases: {
                    failed: backendJa.tools.automation.phases.failed,
                    loading: backendJa.tools.automation.phases.loading,
                    ready: backendJa.tools.automation.phases.ready,
                    unloaded: backendJa.tools.automation.phases.unloaded,
                },
                primaryDisplay: backendJa.tools.automation.primaryDisplay,
                profiles: backendJa.tools.automation.profiles,
                range: backendJa.tools.automation.range,
                reason: backendJa.tools.automation.reason,
                renderer: backendJa.tools.automation.renderer,
                repeated: backendJa.tools.automation.repeated,
                requestId: backendJa.tools.automation.requestId,
                size: backendJa.tools.automation.size,
                stopShortcut: backendJa.tools.automation.stopShortcut,
                stopped: backendJa.tools.automation.stopped,
                truncated: backendJa.tools.automation.truncated,
                unavailable: backendJa.tools.automation.unavailable,
                untitled: backendJa.tools.automation.untitled,
                uploaded: backendJa.tools.automation.uploaded,
                userControlled: backendJa.tools.automation.userControlled,
                visible: backendJa.tools.automation.visible,
                windowVisible: backendJa.tools.automation.windowVisible,
            },
            error: backendJa.modules.mcp.status.error,
            file: {
                createDirectoryPanel: {
                    failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                },
                deleteFilePanel: {
                    failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
            media: {
                cropImagePanel: {
                    status: {
                        error: backendJa.modules.mcp.status.error,
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                generateImagePanel: {
                    status: {
                        error: backendJa.modules.mcp.status.error,
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                removeBackgroundPanel: {
                    status: {
                        error: backendJa.modules.mcp.status.error,
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                resizeImagePanel: {
                    status: {
                        error: backendJa.modules.mcp.status.error,
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                rotateImagePanel: {
                    status: {
                        error: backendJa.modules.mcp.status.error,
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
            },
            platform: {
                file: {
                    actions: {
                        delete: backendJa.tools.platform.file.actions.delete,
                        edit: backendJa.tools.platform.file.actions.edit,
                        list: backendJa.tools.platform.file.actions.list,
                        read: backendJa.tools.platform.file.actions.read,
                        write: backendJa.tools.platform.file.actions.write,
                    },
                    after: backendJa.tools.platform.file.after,
                    before: backendJa.tools.platform.file.before,
                    deleted: backendJa.tools.platform.file.deleted,
                    empty: backendJa.tools.platform.file.empty,
                    matchLimit: backendJa.tools.platform.file.matchLimit,
                    matches: backendJa.tools.platform.file.matches,
                    nextLine: backendJa.tools.platform.file.nextLine,
                    noMatches: backendJa.tools.platform.file.noMatches,
                    range: backendJa.tools.platform.file.range,
                    requested: backendJa.tools.platform.file.requested,
                    saved: backendJa.tools.platform.file.saved,
                    scanLimit: backendJa.tools.platform.file.scanLimit,
                    scanned: backendJa.tools.platform.file.scanned,
                },
                memory: {
                    affected: backendJa.tools.platform.memory.affected,
                    append: backendJa.tools.platform.memory.append,
                    apply: backendJa.tools.platform.memory.apply,
                    confidence: {
                        confirmed: backendJa.tools.platform.memory.confidence.confirmed,
                        disputed: backendJa.tools.platform.memory.confidence.disputed,
                        inferred: backendJa.tools.platform.memory.confidence.inferred,
                    },
                    conflicts: backendJa.tools.platform.memory.conflicts,
                    dependencies: backendJa.tools.platform.memory.dependencies,
                    empty: backendJa.tools.platform.memory.empty,
                    kinds: {
                        event: backendJa.tools.platform.memory.kinds.event,
                        experience: backendJa.tools.platform.memory.kinds.experience,
                        fact: backendJa.tools.platform.memory.kinds.fact,
                        preference: backendJa.tools.platform.memory.kinds.preference,
                        procedure: backendJa.tools.platform.memory.kinds.procedure,
                        project: backendJa.tools.platform.memory.kinds.project,
                        summary: backendJa.tools.platform.memory.kinds.summary,
                    },
                    omitted: backendJa.tools.platform.memory.omitted,
                    origins: {
                        fiction: backendJa.tools.platform.memory.origins.fiction,
                        import: backendJa.tools.platform.memory.origins.import,
                        model: backendJa.tools.platform.memory.origins.model,
                        tool: backendJa.tools.platform.memory.origins.tool,
                        user: backendJa.tools.platform.memory.origins.user,
                    },
                    pageRange: backendJa.tools.platform.memory.pageRange,
                    preview: backendJa.tools.platform.memory.preview,
                    previewIds: backendJa.tools.platform.memory.previewIds,
                    recordPage: backendJa.tools.platform.memory.recordPage,
                    records: backendJa.tools.platform.memory.records,
                    removed: backendJa.tools.platform.memory.removed,
                    requested: backendJa.tools.platform.memory.requested,
                    requiredBudget: backendJa.tools.platform.memory.requiredBudget,
                    retract: backendJa.tools.platform.memory.retract,
                    root: backendJa.tools.platform.memory.root,
                    saved: backendJa.tools.platform.memory.saved,
                    scopeKinds: {
                        group: backendJa.tools.platform.memory.scopeKinds.group,
                        library: backendJa.tools.platform.memory.scopeKinds.library,
                        personal: backendJa.tools.platform.memory.scopeKinds.personal,
                        workspace: backendJa.tools.platform.memory.scopeKinds.workspace,
                    },
                    scopes: backendJa.tools.platform.memory.scopes,
                    source: backendJa.tools.platform.memory.source,
                    sourcePage: backendJa.tools.platform.memory.sourcePage,
                    sources: backendJa.tools.platform.memory.sources,
                    topics: backendJa.tools.platform.memory.topics,
                    truncated: backendJa.tools.platform.memory.truncated,
                    unavailable: backendJa.tools.platform.memory.unavailable,
                },
                nextCursor: backendJa.tools.platform.nextCursor,
                nextOffset: backendJa.tools.platform.nextOffset,
                noData: backendJa.tools.platform.noData,
                partial: backendJa.tools.platform.partial,
                process: {
                    actions: {
                        input: backendJa.tools.platform.process.actions.input,
                        read: backendJa.tools.platform.process.actions.read,
                        stop: backendJa.tools.platform.process.actions.stop,
                    },
                    exited: backendJa.tools.platform.process.exited,
                    input: backendJa.tools.platform.process.input,
                    noOutput: backendJa.tools.platform.process.noOutput,
                    output: backendJa.tools.platform.process.output,
                    running: backendJa.tools.platform.process.running,
                    truncated: backendJa.tools.platform.process.truncated,
                    unknown: backendJa.tools.platform.process.unknown,
                },
                team: {
                    actions: {
                        claim: backendJa.tools.platform.team.actions.claim,
                        claim_ready: backendJa.tools.platform.team.actions.claim_ready,
                        complete: backendJa.tools.platform.team.actions.complete,
                        create: backendJa.tools.platform.team.actions.create,
                        get: backendJa.tools.platform.team.actions.get,
                        list: backendJa.tools.platform.team.actions.list,
                        release: backendJa.tools.platform.team.actions.release,
                        set_dependencies: backendJa.tools.platform.team.actions.set_dependencies,
                    },
                    assigned: backendJa.tools.platform.team.assigned,
                    blockedBy: backendJa.tools.platform.team.blockedBy,
                    dependencies: backendJa.tools.platform.team.dependencies,
                    empty: backendJa.tools.platform.team.empty,
                    emptyEvents: backendJa.tools.platform.team.emptyEvents,
                    events: {
                        member_changed: backendJa.tools.platform.team.events.member_changed,
                        message_queued: backendJa.tools.platform.team.events.message_queued,
                        task_claimed: backendJa.tools.platform.team.events.task_claimed,
                        task_completed: backendJa.tools.platform.team.events.task_completed,
                        task_created: backendJa.tools.platform.team.events.task_created,
                        task_dependencies_changed: backendJa.tools.platform.team.events.task_dependencies_changed,
                        task_released: backendJa.tools.platform.team.events.task_released,
                    },
                    moreEvents: backendJa.tools.platform.team.moreEvents,
                    nextTasks: backendJa.tools.platform.team.nextTasks,
                    noProgress: backendJa.tools.platform.team.noProgress,
                    noReady: backendJa.tools.platform.team.noReady,
                    ready: backendJa.tools.platform.team.ready,
                    reasons: {
                        events: backendJa.tools.platform.team.reasons.events,
                        no_progress: backendJa.tools.platform.team.reasons.no_progress,
                        ready_work: backendJa.tools.platform.team.reasons.ready_work,
                        timeout: backendJa.tools.platform.team.reasons.timeout,
                    },
                    task: backendJa.tools.platform.team.task,
                    unclaimed: backendJa.tools.platform.team.unclaimed,
                },
                version: backendJa.tools.platform.version,
            },
            presentation: {
                appendedContent: backendJa.tools.presentation.appendedContent,
                characters: backendJa.tools.presentation.characters,
                contentUnavailable: backendJa.tools.presentation.contentUnavailable,
                findFiles: {
                    continuationDetails: backendJa.tools.presentation.findFiles.continuationDetails,
                    excludeSources: {
                        argument: backendJa.tools.presentation.findFiles.excludeSources.argument,
                        fallback: backendJa.tools.presentation.findFiles.excludeSources.fallback,
                        settings: backendJa.tools.presentation.findFiles.excludeSources.settings,
                        unknown: backendJa.tools.presentation.findFiles.excludeSources.unknown,
                    },
                    exclusions: backendJa.tools.presentation.findFiles.exclusions,
                    expandPage: backendJa.tools.presentation.findFiles.expandPage,
                    nextPage: backendJa.tools.presentation.findFiles.nextPage,
                    pageFiles: backendJa.tools.presentation.findFiles.pageFiles,
                    pageOffset: backendJa.tools.presentation.findFiles.pageOffset,
                    restartAfterFailure: backendJa.tools.presentation.findFiles.restartAfterFailure,
                    returnedFiles: backendJa.tools.presentation.findFiles.returnedFiles,
                    workspaceErrors: backendJa.tools.presentation.findFiles.workspaceErrors,
                },
                gotoDefinition: {
                    contentTruncated: backendJa.tools.presentation.gotoDefinition.contentTruncated,
                    emptyPage: backendJa.tools.presentation.gotoDefinition.emptyPage,
                    nextPage: backendJa.tools.presentation.gotoDefinition.nextPage,
                    pageSummary: backendJa.tools.presentation.gotoDefinition.pageSummary,
                },
                historyMessages: backendJa.tools.presentation.historyMessages,
                invalidatedNote: backendJa.tools.presentation.invalidatedNote,
                mainAgent: backendJa.tools.presentation.mainAgent,
                messageBody: backendJa.tools.presentation.messageBody,
                messageSaved: backendJa.tools.presentation.messageSaved,
                moreHistory: backendJa.tools.presentation.moreHistory,
                noteContent: backendJa.tools.presentation.noteContent,
                noteDirectory: backendJa.tools.presentation.noteDirectory,
                partialContent: backendJa.tools.presentation.partialContent,
                recipient: backendJa.tools.presentation.recipient,
            },
            reject: backendJa.tools.file.diffCodeLens.reject,
            subagents: {
                completed: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
            },
            terminal: {
                executeCommandPanel: {
                    status: {
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
            },
        },
    },
    composables: {
        useAttachments: {
            errors: {
                readFileFailed: backendJa.webview.errors.readFileFailed,
            },
        },
    },
    errors: {
        cancelled: backendJa.errors.cancelled,
        unknown: backendJa.errors.unknown,
    },
    stores: {
        chatStore: {
            errors: {
                restoreCheckpointFailed: backendJa.modules.checkpoint.errors.restoreFailed,
                unknownError: backendJa.modules.api.chat.errors.unknownError,
            },
        },
        terminalStore: {
            errors: {
                killTerminalFailed: backendJa.webview.errors.killTerminalFailed,
            },
        },
    },
};

export default sharedJa;
