/**
 * AUTO-GENERATED by scripts/generate-tool-meta.mjs — 请勿手改！
 *
 * 单一来源：backend/tools 下各工具文件的 ToolDeclaration（工具名 / description / 参数 schema）。
 * 只包含「可静态求值」的确定性字段；运行时动态构造的 description/参数被省略并置
 * descriptionDynamic / parametersDynamic 标记（前端据此回退手写文案）。
 * 重新生成：node scripts/generate-tool-meta.mjs
 */
export interface ToolMetaParameterItem {
  type: string
  description?: string
  enum?: string[]
}

export interface ToolMetaParameter {
  type: string
  description?: string
  enum?: string[]
  default?: string | number | boolean
  required?: boolean
  items?: ToolMetaParameterItem
}

export interface ToolMeta {
  /** 工具声明描述（仅静态可提取；运行时动态构造时省略并置 descriptionDynamic） */
  description?: string
  descriptionDynamic?: boolean
  /** 顶层参数摘要：参数名 → { type, description?, enum?, default?, required?, items? } */
  parameters: Record<string, ToolMetaParameter>
  /** parameters 存在无法静态提取的部分时为 true */
  parametersDynamic?: boolean
  /** 声明来源（backend/tools 相对路径），便于核对 */
  source: string
}

export const toolMeta: Record<string, ToolMeta> = {
  'agent_send_message': {
    descriptionDynamic: true,
    parameters: {
      "targetRunId": {"type":"string"},
      "targetAgentName": {"type":"string"},
      "message": {"type":"string","required":true},
      "threadId": {"type":"string"},
    },
    parametersDynamic: true,
    source: "backend/tools/subagents/createAgentMessageDeclaration.ts",
  },
  'apply_diff': {
    descriptionDynamic: true,
    parameters: {
      "path": {"type":"string","required":true},
      "hunks": {"type":"array","items":{"type":"object"}},
      "patch": {"type":"string"},
    },
    parametersDynamic: true,
    source: "backend/tools/file/diff/createApplyDiffDeclaration.ts",
  },
  'compare_review_documents': {
    description: "Compare two review documents under .graycode/review/**.md without modifying them. The result lists findings that were added, removed or carried over, changes in tracking status, and differences in summary statistics.",
    parameters: {
      "basePath": {"type":"string","description":"Path of the earlier review document to compare from.","required":true},
      "targetPath": {"type":"string","description":"Path of the later review document to compare against.","required":true},
      "includeUnchanged": {"type":"boolean","description":"Whether to also list carried-over findings that did not change. Defaults to false."},
    },
    source: "backend/tools/review/compare_review_documentsRuntime.ts",
  },
  'create_design': {
    description: "Create a new Markdown design document under .graycode/design/**.md. This tool only writes the design; it does not create a plan or change any code. If the target file already exists, the call fails; use update_design to revise an existing design.",
    parameters: {
      "title": {"type":"string","description":"Optional design title, also used to build the default file name."},
      "overview": {"type":"string","description":"Optional one-line overview."},
      "design": {"type":"string","description":"Design content in Markdown.","required":true},
      "path": {"type":"string","description":"Optional output path. It must be under .graycode/design/**.md (in a multi-root workspace, workspace/.graycode/design/**.md). If omitted, the path is derived from the title."},
    },
    source: "backend/tools/design/create_designRuntime.ts",
  },
  'create_directory': {
    descriptionDynamic: true,
    parameters: {
      "paths": {"type":"array","items":{"type":"string"},"required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/file/createDirectoryDeclaration.ts",
  },
  'create_plan': {
    description: "Create a new Markdown plan document with a TODO checklist under .graycode/plans/**.md. This tool only writes the plan; it does not carry it out. If the target file already exists, the call fails; use update_plan to revise an existing plan. When the plan is based on a confirmed design or review, pass that document as sourceArtifact so you can later check whether the plan still matches it.",
    parameters: {
      "title": {"type":"string","description":"Optional plan title, also used to build the default file name."},
      "overview": {"type":"string","description":"Optional one-line overview."},
      "plan": {"type":"string","description":"Plan content in Markdown.","required":true},
      "todos": {"type":"array","description":"TODO checklist for the plan. Required; each item has id, content and status.","items":{"type":"object"},"required":true},
      "sourceArtifact": {"type":"object","description":"Optional confirmed design or review document that the plan is based on."},
      "path": {"type":"string","description":"Optional output path. It must be under .graycode/plans/**.md (in a multi-root workspace, workspace/.graycode/plans/**.md). If omitted, the path is derived from the title."},
    },
    source: "backend/tools/plan/create_planRuntime.ts",
  },
  'create_progress': {
    description: "Create the project progress document at .graycode/progress.md, which tracks project status, phase, related documents, TODOs, milestones, risks and a change log. The result is a short progress snapshot rather than the full Markdown. If a valid progress document already exists, the call returns its snapshot with a warning instead of creating a second file; if the existing file is invalid, the call fails. status defaults to active and phase to design.",
    parameters: {
      "path": {"type":"string","description":"Optional output path. It must be .graycode/progress.md (in a multi-root workspace, workspace/.graycode/progress.md)."},
      "projectName": {"type":"string","description":"Optional readable project name. Defaults to the name of the first workspace folder."},
      "projectId": {"type":"string","description":"Optional stable project ID. Defaults to a slug of the project name."},
      "status": {"type":"string","enum":["active","blocked","completed","archived"]},
      "phase": {"type":"string","enum":["design","plan","implementation","review","maintenance"]},
      "currentFocus": {"type":"string"},
      "latestConclusion": {"type":"string"},
      "currentBlocker": {"type":"string"},
      "nextAction": {"type":"string"},
      "activeArtifacts": {"type":"object"},
      "todos": {"type":"array","items":{"type":"object"}},
      "risks": {"type":"array","items":{"type":"object"}},
    },
    source: "backend/tools/progress/create_progressRuntime.ts",
  },
  'create_review': {
    description: "Create a Markdown review document under .graycode/review/**.md and start a review with it. It belongs to Review mode and only writes the review document, never project code. Each review uses one document, and a conversation can have only one review in progress; finalize the current review before creating another. If the target file already exists, the call fails; continue that review with record_review_milestone or finalize_review, or choose a different path.",
    parameters: {
      "title": {"type":"string","description":"Optional review title, also used to build the default file name."},
      "overview": {"type":"string","description":"Optional one-line overview of the review."},
      "review": {"type":"string","description":"Initial review content in Markdown, such as scope and approach.","required":true},
      "path": {"type":"string","description":"Optional output path. It must be under .graycode/review/**.md (in a multi-root workspace, workspace/.graycode/review/**.md). If omitted, the path is derived from the title."},
    },
    source: "backend/tools/review/create_reviewRuntime.ts",
  },
  'crop_image': {
    descriptionDynamic: true,
    parameters: {
      "images": {"type":"array","items":{"type":"object"}},
      "image_path": {"type":"string"},
      "output_path": {"type":"string"},
      "x1": {"type":"integer"},
      "y1": {"type":"integer"},
      "x2": {"type":"integer"},
      "y2": {"type":"integer"},
    },
    parametersDynamic: true,
    source: "backend/tools/media/crop_imageRuntime.ts",
  },
  'delete_code': {
    descriptionDynamic: true,
    parameters: {
      "files": {"type":"array","items":{"type":"object"},"required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/file/createDeleteCodeDeclaration.ts",
  },
  'delete_file': {
    descriptionDynamic: true,
    parameters: {
      "paths": {"type":"array","items":{"type":"string"},"required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/file/createDeleteFileDeclaration.ts",
  },
  'execute_command': {
    descriptionDynamic: true,
    parameters: {
      "command": {"type":"string","required":true},
      "cwd": {"type":"string"},
      "shell": {"type":"string","default":"default"},
      "timeout": {"type":"number"},
      "background": {"type":"boolean"},
    },
    parametersDynamic: true,
    source: "backend/tools/terminal/processRunnerRuntime.ts",
  },
  'finalize_review': {
    description: "Finish the review in progress: record the final conclusion and decision, tidy the structure of its document under .graycode/review/**.md and update the final summary. path must be the document of the review currently in progress. After this call, no more milestones can be recorded unless the review is reopened with reopen_review.",
    parameters: {
      "path": {"type":"string","description":"Path of the review document, under .graycode/review/**.md.","required":true},
      "conclusion": {"type":"string","description":"Final conclusion of the review.","required":true},
      "overallDecision": {"type":"string","description":"Optional overall decision.","enum":["accepted","conditionally_accepted","rejected","needs_follow_up"]},
      "recommendedNextAction": {"type":"string","description":"Optional recommended next step to show in the summary."},
      "reviewedModules": {"type":"array","description":"Optional modules covered by the review, merged into the summary.","items":{"type":"string"}},
    },
    source: "backend/tools/review/finalize_reviewRuntime.ts",
  },
  'find_files': {
    descriptionDynamic: true,
    parameters: {
      "patterns": {"type":"array","items":{"type":"string"},"required":true},
      "exclude": {"type":"string"},
      "includeIgnored": {"type":"boolean","default":false},
      "maxResults": {"type":"number","default":500},
      "offset": {"type":"integer","default":0},
    },
    parametersDynamic: true,
    source: "backend/tools/search/findFilesRuntime.ts",
  },
  'find_references': {
    descriptionDynamic: true,
    parameters: {
      "path": {"type":"string","required":true},
      "line": {"type":"integer","required":true},
      "column": {"type":"integer"},
      "symbol": {"type":"string"},
      "context": {"type":"number"},
      "maxResults": {"type":"integer","default":500},
      "offset": {"type":"integer","default":0},
      "countOnly": {"type":"boolean","default":false},
    },
    parametersDynamic: true,
    source: "backend/tools/lsp/declarations.ts",
  },
  'generate_image': {
    descriptionDynamic: true,
    parameters: {
      "images": {"type":"array","items":{"type":"object"}},
    },
    parametersDynamic: true,
    source: "backend/tools/media/generate_imageRuntime.ts",
  },
  'get_activity_stats': {
    description: "Get statistics on how the user spends time in the IDE: how long they have worked, in which blocks, and how long the current stretch has lasted. Use it to understand the user's work and rest rhythm, spot long unbroken sessions, or check whether the user is active right now.\n\nActivity is recorded as separate sessions: 15 or more minutes without activity ends a session, and the next activity starts a new one. A gap therefore means the user left the IDE (a break, sleep or time away), so do not assume they worked continuously from firstActiveAt to lastActiveAt. \"sessions\" covers the last 7 days and lists each day's actual work blocks as local \"HH:mm-HH:mm (Nm)\"; \"gaps\" covers the most recent day and lists the idle intervals between blocks; \"currentSession.startedAt\" is when the ongoing session began, including the date because a session can start before midnight. The data holds timestamps only, with no user content, and all times are local (HH:mm or YYYY-MM-DD HH:mm).",
    parameters: {
      "range": {"type":"string","description":"Time range: today, 7d (last 7 days), 30d, 90d, 365d or all (entire history); default 7d.","enum":["today","7d","30d","90d","365d","all"]},
      "includeHourly": {"type":"boolean","description":"Whether to include an hourly heatmap (24 slots per day with active minutes per hour, local time), which helps when analyzing the user's sleep and work schedule; default false."},
      "includeMonthly": {"type":"boolean","description":"Whether to include monthly totals (minutes, active days and session count per month) for a long-term overview; default false."},
    },
    source: "backend/tools/activity/activityRuntime.ts",
  },
  'get_symbols': {
    descriptionDynamic: true,
    parameters: {
      "paths": {"type":"array","items":{"type":"string"},"required":true},
      "maxDepth": {"type":"integer","default":1},
      "kinds": {"type":"array","items":{"type":"string"}},
    },
    parametersDynamic: true,
    source: "backend/tools/lsp/declarations.ts",
  },
  'goto_definition': {
    descriptionDynamic: true,
    parameters: {
      "path": {"type":"string","required":true},
      "line": {"type":"integer","required":true},
      "column": {"type":"integer"},
      "symbol": {"type":"string"},
      "maxResults": {"type":"integer","default":500},
      "offset": {"type":"integer","default":0},
    },
    parametersDynamic: true,
    source: "backend/tools/lsp/declarations.ts",
  },
  'history_search': {
    descriptionDynamic: true,
    parameters: {
      "mode": {"type":"string","enum":["search","read"],"required":true},
      "query": {"type":"string"},
      "is_regex": {"type":"boolean"},
      "start_line": {"type":"integer"},
      "end_line": {"type":"integer"},
    },
    parametersDynamic: true,
    source: "backend/tools/history/history_search.ts",
  },
  'insert_code': {
    descriptionDynamic: true,
    parameters: {
      "files": {"type":"array","items":{"type":"object"},"required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/file/createInsertCodeDeclaration.ts",
  },
  'list_files': {
    descriptionDynamic: true,
    parameters: {
      "paths": {"type":"array","items":{"type":"string"},"required":true},
      "recursive": {"type":"boolean","default":false},
    },
    parametersDynamic: true,
    source: "backend/tools/file/listFilesRuntime.ts",
  },
  'memory_compress': {
    description: "处理待压缩的工程日志记忆。记忆按二叉树组织：相邻的两条记忆合并成一行摘要，摘要再两两合并。\n不传 blockId 和 summary 时，返回下一个待压缩的提示；按提示写好摘要后，再用 blockId 和 summary 提交。\n成功的 memory_note 或 memory_wake 返回的 pendingCompression 是可延后的维护提示，不要因此中断当前用户任务；memory_wake 因缺少摘要失败时才必须立即处理。\n开始维护后按提示顺序执行；不同作用域的独立压缩可以在同一响应中调用。",
    parameters: {
      "blockId": {"type":"string","description":"要压缩的块 ID，例如 \"0-1\"，从压缩提示中复制。"},
      "summary": {"type":"string"},
      "scope": {"type":"string","description":"记忆作用域。有工作区时默认操作当前工作区记忆；传 \"global\" 操作全局记忆，传 \"workspace\" 显式操作工作区记忆。","enum":["global","workspace"]},
    },
    parametersDynamic: true,
    source: "backend/tools/memory/memory_compressRuntime.ts",
  },
  'memory_config': {
    description: "查看或修改工程日志记忆的配置。不传参数时返回当前配置；传入参数时只修改对应的项。\n这些配置控制 memory_wake 的输出篇幅、分页方式和以后写入的单条长度上限，修改后不会改写已保存的记忆。",
    parameters: {
      "wakeLines": {"type":"number","description":"memory_wake 输出的行数预算，默认 96（约 8k tokens）。值越大，保留的细节越多。"},
      "entryChars": {"type":"number"},
      "partChars": {"type":"number","description":"每个输出部分的最大字符数，默认 20000。"},
      "partLines": {"type":"number","description":"每个输出部分的最大行数，默认 500。"},
    },
    parametersDynamic: true,
    source: "backend/tools/memory/memory_configRuntime.ts",
  },
  'memory_forget': {
    description: "丢弃有误的工程日志树摘要，或删除原始记忆。具体行为取决于 blockId 的写法：\n- 用短横线表示的块，例如 \"16-31\"：只丢弃这个摘要及其上层摘要，原始记忆保持不变。\n- 单个数字，例如 \"5\"：删除这一条原始记忆，之后的记忆 ID 依次前移。\n- 用逗号表示的闭区间，例如 \"1,3\"：删除 ID 1 到 3（含两端）的所有原始记忆。",
    parameters: {
      "blockId": {"type":"string","description":"要处理的块 ID（如 \"16-31\"）、单个记忆 ID（如 \"5\"）或闭区间（如 \"1,3\"）。","required":true},
      "scope": {"type":"string","description":"记忆作用域。有工作区时默认操作当前工作区记忆；传 \"global\" 操作全局记忆，传 \"workspace\" 显式操作工作区记忆。","enum":["global","workspace"]},
    },
    source: "backend/tools/memory/memory_forgetRuntime.ts",
  },
  'memory_note': {
    description: "记录一条在以后的会话里仍然有用的工程日志，例如项目约定、踩过的坑或长期的技术决定。用户本人的事实、偏好和经历属于个人长期记忆，请用 memory_remember 记录，不要用本工具代替。\n有工作区时，记录保存到当前工作区的记忆中，与全局记忆分开；memory_wake 会同时读取两者。\n不要记录临时进度、工作流水、可以从仓库重新得到的内容、秘密或重复的信息。\n如果结果包含 pendingCompression，它只是可延后的维护提示：不要中断当前用户任务，完成当前交付后再压缩；同一个待压缩状态不会重复提示。",
    parameters: {
      "text": {"type":"string","required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/memory/memory_noteRuntime.ts",
  },
  'memory_recall': {
    description: "用正则表达式逐字搜索工程日志记忆，也就是 memory_note 写下的项目约定和经验。用户的个人长期记忆不在这里，请用 memory_search。\n搜索同时覆盖全局记忆和当前工作区记忆，命中结果以 --- Global memory --- 和 --- Workspace memory --- 标注来源。已被压缩成摘要的原始记忆也在搜索范围内，压缩不会丢失信息。\n结果受单次输出容量限制；被截断时会提示你缩小正则范围。",
    parameters: {
      "regex": {"type":"string","description":"搜索用的正则表达式，不区分大小写，也会匹配记忆的 ID 和日期。","required":true},
    },
    source: "backend/tools/memory/memory_recallRuntime.ts",
  },
  'memory_wake': {
    description: "读取工程日志记忆，也就是 memory_note 写下的项目约定和经验。它和用户的个人长期记忆是两套系统，个人长期记忆请用 memory_search 或 memory_read 查阅。\n在新的工作会话开始、且以往的约定可能影响当前任务时调用；与历史无关、也不需要工具的简单回复不必调用。\n输出分为全局记忆和当前工作区记忆两部分，分别以 --- Global memory --- 和 --- Workspace memory --- 标注。近期的记忆保留原文，较早的记忆以压缩摘要呈现。\n输出较长时会分成多个部分，请按输出末尾的提示依次读取，直到看到 \"You are awake.\" 为止。成功结果中的 pendingCompression 可延后处理，不要中断当前用户任务。",
    parameters: {
      "part": {"type":"integer","description":"要读取的部分号，从 1 开始，默认为 1。"},
      "snapshotT": {"type":"integer","description":"第一次读取时的记忆总数，从输出末尾的提示中复制，用来让后续部分与第一部分保持一致。首次调用不传或传 0，表示使用当前总数。"},
    },
    source: "backend/tools/memory/memory_wakeRuntime.ts",
  },
  'memory_zoom': {
    description: "展开工程日志记忆树中的一个节点，查看它下一层的两个半部分。\nmemory_wake 输出中每一行 #a-b 都是一个节点。逐层展开，最终可以看到原始记忆本身。",
    parameters: {
      "blockId": {"type":"string","description":"要展开的块 ID，例如 \"16-31\"，从 memory_wake 的输出或上一次 memory_zoom 的结果中复制。","required":true},
      "scope": {"type":"string","description":"记忆作用域。有工作区时默认读取当前工作区记忆；传 \"global\" 读取全局记忆，传 \"workspace\" 显式读取工作区记忆。","enum":["global","workspace"]},
    },
    source: "backend/tools/memory/memory_zoomRuntime.ts",
  },
  'read_file': {
    descriptionDynamic: true,
    parameters: {
      "path": {"type":"string"},
      "files": {"type":"array","items":{"type":"object"}},
      "startLine": {"type":"integer"},
      "endLine": {"type":"integer"},
    },
    parametersDynamic: true,
    source: "backend/tools/file/readFileRuntime.ts",
  },
  'read_skill': {
    descriptionDynamic: true,
    parameters: {
      "name": {"type":"string","required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/skills/readSkillRuntime.ts",
  },
  'record_progress_milestone': {
    description: "Record a project-level milestone in .graycode/progress.md and return the refreshed progress snapshot. It is meant for project progress points, not for review findings or plan content. If milestoneId is omitted, the next ID (PG1, PG2, ...) is generated, and an existing ID makes the call fail. status defaults to completed, in which case completedAt defaults to now. latestConclusion, currentBlocker and nextAction also update the document summary.",
    parameters: {
      "path": {"type":"string","description":"Optional target path. It must be .graycode/progress.md (in a multi-root workspace, workspace/.graycode/progress.md)."},
      "milestoneId": {"type":"string"},
      "title": {"type":"string","required":true},
      "status": {"type":"string","enum":["in_progress","completed"]},
      "summary": {"type":"string","required":true},
      "relatedTodoIds": {"type":"array","items":{"type":"string"}},
      "relatedReviewMilestoneIds": {"type":"array","items":{"type":"string"}},
      "relatedArtifacts": {"type":"object"},
      "startedAt": {"type":"string"},
      "completedAt": {"type":"string"},
      "nextAction": {"type":"string"},
      "latestConclusion": {"type":"string"},
      "currentBlocker": {"type":"string"},
    },
    source: "backend/tools/progress/record_progress_milestoneRuntime.ts",
  },
  'record_review_milestone': {
    description: "Add a milestone to the review in progress and update the summary, findings and statistics of its document under .graycode/review/**.md. path must be the document of the review currently in progress in this conversation. After finalize_review, milestones can no longer be recorded unless the review is reopened with reopen_review.",
    parameters: {
      "path": {"type":"string","description":"Path of the review document, under .graycode/review/**.md.","required":true},
      "milestoneId": {"type":"string","description":"Optional milestone ID. Generated automatically if omitted."},
      "milestoneTitle": {"type":"string","description":"Milestone title.","required":true},
      "summary": {"type":"string","description":"Milestone summary in Markdown.","required":true},
      "status": {"type":"string","description":"Milestone status.","enum":["in_progress","completed"]},
      "conclusion": {"type":"string","description":"Optional latest conclusion to show in the review summary."},
      "evidenceFiles": {"type":"array","description":"Optional file paths that serve as evidence. Use them when you cannot point to specific lines.","items":{"type":"string"}},
      "evidence": {"type":"array","description":"Optional evidence references, each with a file path and optional lines, symbol or excerpt hash.","items":{"type":"object"}},
      "findings": {"type":"array","description":"Optional findings as plain text, merged into the findings section. Prefer structuredFindings.","items":{"type":"string"}},
      "structuredFindings": {"type":"array","description":"Optional structured findings, merged into the findings section. Keep each title short and put the explanation in description.","items":{"type":"object"}},
      "reviewedModules": {"type":"array","description":"Optional modules covered by the review, merged into the review summary.","items":{"type":"string"}},
      "recommendedNextAction": {"type":"string","description":"Optional recommended next step to show in the review summary."},
    },
    source: "backend/tools/review/record_review_milestoneRuntime.ts",
  },
  'remove_background': {
    descriptionDynamic: true,
    parameters: {
      "images": {"type":"array","items":{"type":"object"}},
      "image_path": {"type":"string"},
      "output_path": {"type":"string"},
      "subject_description": {"type":"string"},
      "mask_path": {"type":"string"},
    },
    parametersDynamic: true,
    source: "backend/tools/media/remove_backgroundRuntime.ts",
  },
  'reopen_review': {
    description: "Reopen a finalized review document under .graycode/review/**.md so the same review can continue recording milestones. The call fails if another review is already in progress in this conversation.",
    parameters: {
      "path": {"type":"string","description":"Path of the finalized review document, under .graycode/review/**.md.","required":true},
    },
    source: "backend/tools/review/reopen_reviewRuntime.ts",
  },
  'resize_image': {
    descriptionDynamic: true,
    parameters: {
      "images": {"type":"array","items":{"type":"object"}},
      "image_path": {"type":"string"},
      "output_path": {"type":"string"},
      "width": {"type":"integer"},
      "height": {"type":"integer"},
    },
    parametersDynamic: true,
    source: "backend/tools/media/resize_imageRuntime.ts",
  },
  'rotate_image': {
    descriptionDynamic: true,
    parameters: {
      "images": {"type":"array","items":{"type":"object"}},
      "image_path": {"type":"string"},
      "output_path": {"type":"string"},
      "angle": {"type":"number"},
      "format": {"type":"string"},
    },
    parametersDynamic: true,
    source: "backend/tools/media/rotate_imageRuntime.ts",
  },
  'search_in_files': {
    descriptionDynamic: true,
    parameters: {
      "mode": {"type":"string","enum":["search","replace"],"default":"search"},
      "query": {"type":"string","required":true},
      "path": {"type":"string","default":"."},
      "pattern": {"type":"string","default":"**/*"},
      "isRegex": {"type":"boolean","default":false},
      "keywordFallback": {"type":"boolean","default":false},
      "includeIgnored": {"type":"boolean","default":false},
      "caseSensitive": {"type":"boolean"},
      "maxResults": {"type":"number","default":100},
      "context": {"type":"integer"},
      "offset": {"type":"integer","default":0},
      "replace": {"type":"string"},
      "maxFiles": {"type":"number","default":50},
    },
    parametersDynamic: true,
    source: "backend/tools/search/declarationRuntime.ts",
  },
  'show_windows_notification': {
    description: "Show a Windows system notification with a title and message. Use it to reach the user outside the chat, for example when a long task finishes, user action is needed, or an important status changes. On other platforms the tool reports that notifications are not supported.",
    parameters: {
      "title": {"type":"string","description":"Notification title; keep it short and clear.","required":true},
      "message": {"type":"string","description":"Notification body, summarizing what the user needs to know.","required":true},
      "silent": {"type":"boolean","description":"Whether to play the notification without sound; default true."},
      "openChatOnClick": {"type":"boolean","description":"Whether clicking the notification opens the GrayCode chat view; default true."},
    },
    source: "backend/tools/notification/showWindowsNotificationRuntime.ts",
  },
  'subagents': {
    descriptionDynamic: true,
    parameters: {
      "agentName": {"type":"string","required":true},
      "prompt": {"type":"string","required":true},
      "context": {"type":"string"},
      "continueFromRunId": {"type":"string"},
      "maxRuntime": {"type":"integer"},
      "background": {"type":"boolean"},
    },
    parametersDynamic: true,
    source: "backend/tools/subagents/createDeclaration.ts",
  },
  'todo_update': {
    description: "Update individual items in the current conversation's TODO list without rewriting the whole list. Operations run in order. add needs id and content, and status defaults to pending; set_status needs id and status; set_content needs id and content; cancel and remove need only id. The result reports summary counts, invalid operations and ids that were not found, not the full list.",
    parameters: {
      "ops": {"type":"array","description":"Operations to apply to the current TODO list, in order.","items":{"type":"object"},"required":true},
    },
    source: "backend/tools/todo/todo_update.ts",
  },
  'todo_write': {
    description: "Create or replace the TODO list for the current conversation. Use it to set up the list, or to rewrite it as a whole; the todos you pass replace the previous list. To change the status or content of individual items, use todo_update. The result reports item counts, not the full list.",
    parameters: {
      "todos": {"type":"array","description":"The complete list of TODO items.","items":{"type":"object"},"required":true},
    },
    source: "backend/tools/todo/todo_write.ts",
  },
  'update_design': {
    description: "Revise an existing Markdown design document under .graycode/design/**.md. Use it when the user wants to change the current design rather than start a new one. The content you pass replaces the whole document, and the file must already exist.",
    parameters: {
      "path": {"type":"string","description":"Path of the existing design document, under .graycode/design/**.md (in a multi-root workspace, workspace/.graycode/design/**.md).","required":true},
      "title": {"type":"string","description":"Optional updated design title."},
      "overview": {"type":"string","description":"Optional updated one-line overview."},
      "design": {"type":"string","description":"The complete updated design in Markdown.","required":true},
      "changeSummary": {"type":"string","description":"Optional short summary of what changed in this revision."},
    },
    source: "backend/tools/design/update_designRuntime.ts",
  },
  'update_plan': {
    description: "Update an existing Markdown plan document under .graycode/plans/**.md. revision mode (the default) rewrites the plan, which then needs to be confirmed again. progress_sync only updates TODO status during implementation and leaves the plan body unchanged, so send only path, todos, updateMode and the optional changeSummary. sourceArtifact and other carry-over fields (such as sourcePath, planContent or continuationIntent) only make sense in revision mode and should not be sent with progress_sync; a sourceArtifact sent there is ignored with a warning, and fields outside this schema make the call fail.",
    parameters: {
      "path": {"type":"string","description":"Path of the existing plan document, under .graycode/plans/**.md. Reuse the path of the approved plan.","required":true},
      "title": {"type":"string","description":"Optional updated plan title."},
      "overview": {"type":"string","description":"Optional updated one-line overview."},
      "plan": {"type":"string","description":"The complete updated plan in Markdown. Required in revision mode and not used in progress_sync."},
      "todos": {"type":"array","description":"The complete TODO checklist; it replaces the previous one.","items":{"type":"object"},"required":true},
      "updateMode": {"type":"string","description":"revision (default) rewrites the plan and requires confirmation again. progress_sync only updates TODO status and accepts only path, todos, updateMode and changeSummary.","enum":["revision","progress_sync"]},
      "sourceArtifact": {"type":"object","description":"Optional confirmed design or review document to link the plan to; if omitted, the existing link is kept. Only used in revision mode, and ignored with a warning in progress_sync."},
      "changeSummary": {"type":"string","description":"Optional short summary of what changed in this update."},
    },
    source: "backend/tools/plan/update_planRuntime.ts",
  },
  'update_progress': {
    description: "Update the existing project progress document at .graycode/progress.md. Only the fields you pass are changed: activeArtifacts updates only the keys you provide, todos and risks replace their whole lists, and appendLog adds entries to the end of the log. The result is a short progress snapshot that lists the changed sections.",
    parameters: {
      "path": {"type":"string","description":"Optional target path. It must be .graycode/progress.md (in a multi-root workspace, workspace/.graycode/progress.md)."},
      "status": {"type":"string","enum":["active","blocked","completed","archived"]},
      "phase": {"type":"string","enum":["design","plan","implementation","review","maintenance"]},
      "currentFocus": {"type":"string"},
      "latestConclusion": {"type":"string"},
      "currentBlocker": {"type":"string"},
      "nextAction": {"type":"string"},
      "activeArtifacts": {"type":"object"},
      "todos": {"type":"array","items":{"type":"object"}},
      "risks": {"type":"array","items":{"type":"object"}},
      "appendLog": {"type":"array","items":{"type":"object"}},
    },
    source: "backend/tools/progress/update_progressRuntime.ts",
  },
  'validate_progress_document': {
    description: "Check the progress document at .graycode/progress.md without modifying it. The result reports problems with its metadata, section order and basic consistency rules.",
    parameters: {
      "path": {"type":"string","description":"Path of the progress document. It must be .graycode/progress.md (in a multi-root workspace, workspace/.graycode/progress.md).","required":true},
    },
    source: "backend/tools/progress/validate_progress_documentRuntime.ts",
  },
  'validate_review_document': {
    description: "Check an existing review document under .graycode/review/**.md without modifying it. The result reports problems with its format, metadata and consistency rules.",
    parameters: {
      "path": {"type":"string","description":"Path of the review document, under .graycode/review/**.md.","required":true},
    },
    source: "backend/tools/review/validate_review_documentRuntime.ts",
  },
  'write_file': {
    descriptionDynamic: true,
    parameters: {
      "path": {"type":"string","required":true},
      "content": {"type":"string","required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/file/createWriteFileDeclaration.ts",
  },
};
