/** 两种常规上下文管理方式共用同一条请求前缀，不另换总结模型。 */
export type ContextManagementMethod = 'summary' | 'notes';
export const DEFAULT_CONTEXT_MANAGEMENT_METHOD: ContextManagementMethod = 'summary';
export type ContextUserMessageRetention = 'first' | 'all';
export const DEFAULT_USER_MESSAGE_RETENTION: ContextUserMessageRetention = 'first';
export const CONTEXT_TOOL_NAMES = ['context_history', 'context_notes', 'new_context'] as const;

export const CONTEXT_NOTES_GUIDANCE = `This task can continue across context windows. Use context_notes to maintain working notes. As useful constraints, decisions, observations, hypotheses, lessons or next steps become clear, batch them with action=record: cite actual history sources, retain conditions and reasons, and connect requires/supports/applies_to relations. Use supersedes for an explicit replacement; keep unresolved contradictions visible. Do not turn an inference into a user requirement. Before a dependent step or after a context change, use action=recall with the current intent or taskId and an explicit tokenBudget. Recall follows relevant evidence relations and omits text already in the visible context; inspect(noteId) explicitly rereads a note, and context_history reads exact source messages and excerpts. Check omitted, unavailable and missingDependencies before assuming the evidence is complete. Save useful notes before new_context. Changing context continues the same unfinished task. Note events and retrieved results are fixed historical snapshots: record corrections as new events, never rewrite earlier tool results or the request prefix. Ordinary write/append/list/read notes remain available.`;

export const CONTEXT_NOTES_REMINDER = `The current context window is approaching its limit. Preserve useful constraints, decisions, evidence and unfinished steps with context_notes (batch record or a working checkpoint), then call new_context to continue the same task. In the new window, recall the relevant task and its dependencies with a bounded tokenBudget. Do not produce a final answer merely because the context window is changing.`;
